# Exception Handling

# arr = ['mango', 'apple', 'strawberry']

# for i in range(4): #this will give error
#     print(arr[i])

# print('this line has to be executed. its mandatory')



# exception handling with try except block
# arr = ['mango', 'apple', 'strawberry']

# try:
#     for i in range(4):
#         print(arr[i])
# except:
#     print('Exception handled')

# print('this line has to be executed. its mandatory')